#!/usr/bin/env bash
# ProtoMotions Training Launch Script
# Generated by kimodo_pipeline
set -e

echo "=========================================="
echo " ProtoMotions: G1 Motion Tracking Training"
echo "=========================================="
echo ""
echo " Framework:   isaac_lab"
echo " Num envs:    4096"
echo " Max iters:   5000"
echo " Motion dir:  data/motions_g1"
echo ""

# Ensure ProtoMotions repo is cloned
if [ ! -d "ProtoMotions" ]; then
    echo "Cloning ProtoMotions..."
    git clone https://github.com/NVlabs/ProtoMotions.git
    cd ProtoMotions && pip install -e . && cd ..
fi

cd ProtoMotions

# Run training with Hydra config
python protomotions/train.py \
    robot=unitree_g1 \
    motion.dir=data/motions_g1 \
    simulation.framework=isaac_lab \
    simulation.num_envs=4096 \
    training.max_iterations=5000 \
    training.save_interval=100 \
    export.format=onnx \
    export.output_dir=data/policies/ \
    --headless

echo ""
echo "Training complete!"
echo "Policy exported to: data/policies/"
